# Generated by Django 5.2.8 on 2025-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อกิจกรรม')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('date', models.DateField(verbose_name='วันที่จัด')),
                ('capacity', models.IntegerField(verbose_name='จำนวนรับ')),
                ('location', models.CharField(max_length=255, verbose_name='สถานที่')),
                ('organizer', models.CharField(max_length=255, verbose_name='หน่วยงานจัด')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='แท็ก')),
                ('category', models.CharField(max_length=100, verbose_name='หมวดหมู่')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='รูปภาพ')),
                ('registered_count', models.IntegerField(default=0, verbose_name='จำนวนผู้ลงทะเบียน')),
                ('status', models.CharField(choices=[('กำลังรับสมัคร', 'กำลังรับสมัคร'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('สิ้นสุดแล้ว', 'สิ้นสุดแล้ว')], default='กำลังรับสมัคร', max_length=50, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
            ],
            options={
                'verbose_name': 'กิจกรรม',
                'verbose_name_plural': 'กิจกรรม',
                'ordering': ['-created_at'],
            },
        ),
    ]
