# Generated by Django 5.2.8 on 2025-11-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาสิ้นสุด'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาเริ่มต้น'),
        ),
    ]
