# Generated by Django 5.2.8 on 2025-12-06 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_end_time_activity_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('status', models.CharField(default='registered', max_length=20, verbose_name='สถานะ')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ลงทะเบียน')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='activities.activity', verbose_name='กิจกรรม')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ลงทะเบียน')),
            ],
            options={
                'verbose_name': 'การลงทะเบียน',
                'verbose_name_plural': 'การลงทะเบียน',
                'ordering': ['-registered_at'],
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
