# Generated by Django 5.2.8 on 2025-12-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('academic', 'วิชาการและการเรียนรู้'), ('technology', 'เทคโนโลยีและนวัตกรรม'), ('entertainment', 'บันเทิงและนันทนาการ'), ('sports', 'กีฬาและสุขภาพ'), ('volunteer', 'จิตอาสาและสังคม'), ('career', 'แนะแนวและอาชีพ'), ('other', 'อื่นๆ')], default='other', max_length=50, verbose_name='หมวดหมู่'),
        ),
    ]
