# Generated by Django 5.2.8 on 2025-12-20 14:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อแท็ก')),
                ('icon', models.CharField(blank=True, help_text='Emoji หรือ icon (เช่น 💻, 🎵)', max_length=100, null=True, verbose_name='ไอคอน')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('color', models.CharField(default='#3B82F6', help_text='สีแบบ HEX (เช่น #3B82F6)', max_length=7, verbose_name='สี')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'แท็ก',
                'verbose_name_plural': 'แท็ก',
                'db_table': 'tag',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='แท็ก (เก่า)'),
        ),
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_tags', to='activities.activity')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_tags', to='activities.tag')),
            ],
            options={
                'verbose_name': 'แท็กของกิจกรรม',
                'verbose_name_plural': 'แท็กของกิจกรรม',
                'db_table': 'activity_tag',
                'unique_together': {('activity', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='tag_list',
            field=models.ManyToManyField(blank=True, related_name='activities', through='activities.ActivityTag', to='activities.tag', verbose_name='แท็ก'),
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicit_score', models.DecimalField(decimal_places=2, default=0.0, help_text='คะแนนจากการเลือก (0-10)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='คะแนนแบบตรง')),
                ('implicit_score', models.DecimalField(decimal_places=2, default=0.0, help_text='คะแนนจากพฤติกรรม', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='คะแนนจากพฤติกรรม')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='activities.tag', verbose_name='แท็ก')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'ความสนใจของผู้ใช้',
                'verbose_name_plural': 'ความสนใจของผู้ใช้',
                'db_table': 'user_interest',
                'ordering': ['-explicit_score', '-implicit_score'],
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
