# Generated by Django 5.2.8 on 2025-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_tag_alter_activity_tags_activitytag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.TextField(blank=True, help_text='Emoji หรือ icon (เช่น 💻, 🎵)', null=True, verbose_name='ไอคอน'),
        ),
    ]
