# Generated by Django 5.2.8 on 2026-01-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('draft', 'ฉบับร่าง'), ('published', 'เผยแพร่แล้ว'), ('กำลังรับสมัคร', 'กำลังรับสมัคร'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('สิ้นสุดแล้ว', 'สิ้นสุดแล้ว')], default='draft', max_length=50, verbose_name='สถานะ'),
        ),
    ]
