# Generated by Django 5.2.8 on 2026-01-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('กำลังรับสมัคร', 'กำลังรับสมัคร'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('สิ้นสุดแล้ว', 'สิ้นสุดแล้ว')], default='กำลังรับสมัคร', max_length=50, verbose_name='สถานะ'),
        ),
    ]
