# Generated by Django 5.2.8 on 2025-11-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'ฉบับร่าง'), ('published', 'เผยแพร่แล้ว')], default='draft', max_length=20),
        ),
    ]
