# Generated by Django 5.2.8 on 2026-01-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organizer_status',
            field=models.CharField(choices=[('none', 'ทั่วไป'), ('pending', 'รออนุมัติ'), ('approved', 'ผู้จัดกิจกรรม'), ('rejected', 'ไม่อนุมัติ')], default='none', max_length=20, verbose_name='สถานะผู้จัด'),
        ),
    ]
