# Generated by Django 5.2.8 on 2026-01-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_organizer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_doc',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/', verbose_name='เอกสารยืนยันตัวตน'),
        ),
    ]
