# Generated by Django 5.2.8 on 2026-01-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_verification_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='วันเกิด'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(blank=True, choices=[('science', 'คณะวิทยาศาสตร์'), ('engineering', 'คณะวิศวกรรมศาสตร์'), ('business', 'คณะบริหารศาสตร์'), ('liberal_arts', 'คณะศิลปศาสตร์'), ('agriculture', 'คณะเกษตรศาสตร์'), ('nursing', 'คณะพยาบาลศาสตร์'), ('pharmacy', 'คณะเภสัชศาสตร์'), ('law', 'คณะนิติศาสตร์'), ('political', 'คณะรัฐศาสตร์'), ('other', 'อื่นๆ')], max_length=50, null=True, verbose_name='คณะ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ชาย'), ('female', 'หญิง'), ('other', 'อื่นๆ')], max_length=10, null=True, verbose_name='เพศ'),
        ),
    ]
