# Generated by Django 5.2.8 on 2026-01-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_birthdate_userprofile_faculty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verification_doc',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
