# Generated by Django 5.2.8 on 2026-01-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_options_alter_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'โปรไฟล์ผู้ใช้', 'verbose_name_plural': 'โปรไฟล์ผู้ใช้'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verification_doc',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/', verbose_name='เอกสารยืนยันตัวตน'),
        ),
    ]
